defaults:
- data: zarr
- dataloader: native_grid
- datamodule: single # avoid ensembling before we check the single model
- diagnostics: evaluation
- hardware: example
- graph: multi_scale
- model: transformer # Change from default group
- training: default
- _self_

config_validation: True

data:
   resolution: o48 #n320

hardware:
   num_gpus_per_node: 1
   paths:
      output: /home/lennartz/repos/anemoi-test/output
      data: /home/lennartz/repos/anemoi-test/datasets/
      graph: /home/lennartz/repos/anemoi-test/src/graphs
   files:
      dataset: era5-o48-2020-2021-6h-v1.zarr
      graph: duo_gpu_048.pt

training:
   lr:
      rate: 1e-3